#%RAML 0.8
---
title: validations-json-schema
version: 1.0
baseUri: http://localhost:3000/api
schemas:
  - byref: !include validations.json-schema.ref.json
    byname: !include validations.json-schema.external.json
/resources:
  post:
    body:
      application/json:
        schema: |
          {
            "$schema": "http://json-schema.org/draft-03/schema",
            "properties": {
              "id": {
                "description": "Identifier",
                "maxLength": 3,
                "minLength": 3,
                "type": "string"
              },
              "foo": {
                "$ref": "byref"
              }
            },
            "type": "object",
            "name": "resource",
            "required": [ "id", "foo" ]
          }
/external-resources:
  post:
    body:
      application/json:
        schema: byname
